name: Destroy AWS Infra in Multiple Regions

on:
  workflow_dispatch:  # manual trigger from GitHub UI

jobs:
  destroy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us-east-1, us-east-2, eu-west-1, eu-west-2]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ matrix.region }}

    - name: Terraform Init
      run: terraform -chdir=terraform init -reconfigure -backend-config="region=${{ matrix.region }}"

    - name: Terraform Destroy
      run: terraform -chdir=terraform destroy -auto-approve
